# Generated by Django 2.0.6 on 2018-07-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='thing_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
