# Generated by Django 2.0.6 on 2018-08-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20180727_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name': 'thing', 'verbose_name_plural': 'things'},
        ),
    ]
